-- Create research_publications table
CREATE TABLE IF NOT EXISTS research_publications (
    id SERIAL PRIMARY KEY,
    title_of_paper VARCHAR(500) NOT NULL,
    authors TEXT NOT NULL,
    page_no VARCHAR(50),
    publication_journal_title VARCHAR(300) NOT NULL,
    publication_year VARCHAR(4) NOT NULL,
    publisher VARCHAR(200),
    volume_no VARCHAR(50),
    issn_isbn VARCHAR(100),
    scopus_sci_peer_reviewed VARCHAR(20) DEFAULT 'SCI',
    doi VARCHAR(200),
    impact_factor VARCHAR(20),
    type VARCHAR(50) DEFAULT 'Journal',
    level_status VARCHAR(50) DEFAULT 'International',
    status VARCHAR(50) DEFAULT 'Published',
    h_index VARCHAR(20),
    i10_index VARCHAR(20),
    snip VARCHAR(20),
    sjr_index VARCHAR(20),
    published_url TEXT,
    index_terms TEXT,
    issue_no VARCHAR(50),
    conference_name VARCHAR(300),
    event_organizer VARCHAR(200),
    any_awards BOOLEAN DEFAULT false,
    institutional_affiliation BOOLEAN DEFAULT true,
    abstract TEXT,
    upload_file VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Insert sample data
INSERT INTO research_publications (
    title_of_paper, authors, page_no, publication_journal_title, publication_year,
    publisher, volume_no, issn_isbn, scopus_sci_peer_reviewed, doi, impact_factor,
    type, level_status, status, h_index, i10_index, snip, sjr_index, published_url,
    index_terms, issue_no, conference_name, event_organizer, any_awards,
    institutional_affiliation, abstract, upload_file
) VALUES 
(
    'Machine Learning Approaches for Educational Data Mining',
    'Dr. John Smith, Dr. Jane Doe, Dr. Michael Johnson',
    '45-62',
    'Journal of Educational Technology',
    '2024',
    'Springer Nature',
    '15',
    'ISSN: 1234-5678',
    'SCI',
    '10.1007/s12345-024-00123-4',
    '3.45',
    'Journal',
    'International',
    'Published',
    '25',
    '18',
    '1.2',
    '0.8',
    'https://link.springer.com/article/10.1007/s12345-024-00123-4',
    'Machine Learning, Educational Data Mining, Student Performance',
    '3',
    NULL,
    NULL,
    true,
    true,
    'This paper presents novel machine learning approaches for analyzing educational data to improve student learning outcomes.',
    'publication_paper.pdf'
),
(
    'Deep Learning Applications in Computer Vision',
    'Dr. Sarah Wilson, Dr. Robert Brown',
    '123-140',
    'IEEE Transactions on Pattern Analysis',
    '2024',
    'IEEE',
    '46',
    'ISSN: 0162-8828',
    'SCI',
    '10.1109/TPAMI.2024.1234567',
    '4.2',
    'Journal',
    'International',
    'Published',
    '30',
    '22',
    '1.5',
    '1.1',
    'https://ieeexplore.ieee.org/document/1234567',
    'Deep Learning, Computer Vision, Neural Networks',
    '2',
    NULL,
    NULL,
    false,
    true,
    'This research explores advanced deep learning techniques for computer vision applications.',
    'deep_learning_paper.pdf'
),
(
    'Sustainable Energy Solutions for Smart Cities',
    'Dr. Maria Garcia, Dr. David Lee, Dr. Anna Chen',
    '78-95',
    'Renewable Energy Journal',
    '2024',
    'Elsevier',
    '12',
    'ISSN: 0960-1481',
    'SCI',
    '10.1016/j.renene.2024.123456',
    '2.8',
    'Journal',
    'International',
    'Published',
    '20',
    '15',
    '0.9',
    '0.7',
    'https://www.sciencedirect.com/science/article/pii/S0960148124001234',
    'Sustainable Energy, Smart Cities, Renewable Resources',
    '4',
    NULL,
    NULL,
    true,
    true,
    'This study investigates sustainable energy solutions for smart city implementations.',
    'sustainable_energy_paper.pdf'
),
(
    'Artificial Intelligence in Healthcare: A Comprehensive Review',
    'Dr. James Taylor, Dr. Lisa Anderson',
    '200-220',
    'Nature Medicine',
    '2024',
    'Nature Publishing Group',
    '30',
    'ISSN: 1078-8956',
    'SCI',
    '10.1038/s41591-024-12345-6',
    '5.8',
    'Journal',
    'International',
    'Published',
    '35',
    '28',
    '2.1',
    '1.8',
    'https://www.nature.com/articles/s41591-024-12345-6',
    'Artificial Intelligence, Healthcare, Medical Diagnosis',
    '1',
    NULL,
    NULL,
    false,
    true,
    'A comprehensive review of AI applications in healthcare and medical diagnosis.',
    'ai_healthcare_review.pdf'
),
(
    'Blockchain Technology for Supply Chain Management',
    'Dr. Michael Davis, Dr. Jennifer White',
    '150-165',
    'International Conference on Blockchain',
    '2024',
    'ACM',
    NULL,
    'ISBN: 978-1-4503-1234-5',
    'Conference',
    '10.1145/1234567.1234568',
    NULL,
    'Conference',
    'International',
    'Published',
    NULL,
    NULL,
    NULL,
    NULL,
    'https://dl.acm.org/doi/10.1145/1234567.1234568',
    'Blockchain, Supply Chain, Distributed Systems',
    NULL,
    'International Conference on Blockchain',
    'ACM',
    true,
    true,
    'This paper presents a novel blockchain-based approach for supply chain management.',
    'blockchain_supply_chain.pdf'
);
